-- Cada tenant tem banco E credencial proprios: o secret de um nao abre o banco do outro.
CREATE USER tenant_a_user WITH PASSWORD 'senha_a';
CREATE USER tenant_b_user WITH PASSWORD 'senha_b';
CREATE USER tenant_c_user WITH PASSWORD 'senha_c';

CREATE DATABASE tenant_a OWNER tenant_a_user;
CREATE DATABASE tenant_b OWNER tenant_b_user;
CREATE DATABASE tenant_c OWNER tenant_c_user;

REVOKE CONNECT ON DATABASE tenant_a FROM PUBLIC;
REVOKE CONNECT ON DATABASE tenant_b FROM PUBLIC;
REVOKE CONNECT ON DATABASE tenant_c FROM PUBLIC;

-- tenant_a e tenant_b ja nascem com dados.
-- tenant_c nasce VAZIO: a tabela e criada pela propria Lambda no 1o acesso (DatabaseConfig.applySchemaUpdate).

\connect tenant_a tenant_a_user
CREATE TABLE usuario (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL,
    email   VARCHAR(255) NOT NULL,
    senha   VARCHAR(255) NOT NULL
);
INSERT INTO usuario (usuario, email, senha) VALUES
    ('ana.cliente-a',    'ana@cliente-a.com',    '$2a$10$demo.hash.nao.usar.em.producao.aaaaaaaaaaaaaaaaaaaa'),
    ('bruno.cliente-a',  'bruno@cliente-a.com',  '$2a$10$demo.hash.nao.usar.em.producao.aaaaaaaaaaaaaaaaaaaa');

\connect tenant_b tenant_b_user
CREATE TABLE usuario (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL,
    email   VARCHAR(255) NOT NULL,
    senha   VARCHAR(255) NOT NULL
);
INSERT INTO usuario (usuario, email, senha) VALUES
    ('carla.cliente-b',  'carla@cliente-b.com',  '$2a$10$demo.hash.nao.usar.em.producao.bbbbbbbbbbbbbbbbbbbb'),
    ('diego.cliente-b',  'diego@cliente-b.com',  '$2a$10$demo.hash.nao.usar.em.producao.bbbbbbbbbbbbbbbbbbbb'),
    ('elisa.cliente-b',  'elisa@cliente-b.com',  '$2a$10$demo.hash.nao.usar.em.producao.bbbbbbbbbbbbbbbbbbbb');
